name: "{{ project_name }}"
ctxs: "{{ project_ctxs }}"
original_env_schema: "{{ env.repo_dir }}/cloud/linode.schema.yml"
meta:
  template_no_empty_lines: true
cloud:
  repo: "cloud"
  ext_repos:
    - repo: "ext_cloud"
      dir: "ext-cloud"
  collections:
    - namespace: "lrd"
      collection: "ext_cloud"
      path: "ext-cloud/collection"
  hosts:
    type: "template"
    file: "files/hosts.tpl.ini"
    schema: "files/hosts.schema.yml"
main:
  node:
    extend_cloud: true
    nodes:
      - name: "app"
        key: "linode_node"
      - name: "app2"
        key: "linode_node"
        amount: 2
        max_amount: 3
      - name: "app3"
        key: "linode_node"
        hostname: "myapp"
        amount: 3
        max_amount: 5
nodes:
  linode_node:
    service: "node_service"
    base_dir: "/var/cloud"
    credential: "host"
    root: true
    params:
      node_setup:
        setup_log_file: "/var/log/setup.log"
        setup_finished_log_regex: "^Setup Finished.*$"
        setup_success_log_last_line: "Setup Finished - Success"
        initial_connection_timeout: 90
        setup_finished_timeout: 300
services:
  node_service:
    base_dir: "ext-cloud"
    namespace: "ext_node"
    task: "tasks/node/linode/linode.main.node.yml"
    schema: "tasks/node/linode/linode.schema.node.yml"
    validator: "tasks/node/linode/linode.validator.node.yml"
    credentials:
      node: "linode"
    params:
      image: "linode/ubuntu18.04"
      region: "us-east"
      type: "g6-standard-1"
    contents:
      user_data:
        type: "env"
        name: "user_data_ubuntu"
contents:
  user_data_ubuntu:
    type: "template"
    origin: "cloud"
    file: "ext-cloud/files/user-data/ubuntu-18.04.tpl.sh"
    schema: "ext-cloud/files/user-data/ubuntu-18.04.schema.yml"
    credentials:
      node: "host"
    params:
      user_directories: ["/var/cloud"]
      install_docker: true
      install_packages: true
    contents:
      host_ssh_public_keys: "{{ params.host_ssh_public_keys_content | default('') }}"
credentials:
  host:
    host_user: "{{ credentials.host.host_user | default('') }}"
    host_pass: "{{ credentials.host.host_pass | default('') }}"
    ssh_file: "{{ credentials.host.ssh_file | default('') }}"
  linode:
    api_token: "{{ credentials.linode.api_token | default('') }}"
