name: "prometheus-remote"
ctxs: ["remote"]
env:
  repo:
    src: "https://github.com/lucasbasquerotto/env-base.git"
    version: "master"
  repo_dir: "env-base"
  file: "examples/prometheus.yml"
params:
  app_hostname: "prometheus_app"
  db_hostname: "prometheus_db"
  web_hostname: "prometheus_web"
  private_ips: ["{{ params.private_ip }}"]
  cloud_service: "digital_ocean_vpn"
  node_service: "digital_ocean_node"
  dns_provider: "cloudflare"
  main_domain: "{{ params.your_domain }}"
  prometheus_url: "http://prometheus.{{ params.your_domain }}:9090"
  domains:
    grafana: "monitor.{{ params.your_domain }}"
    prometheus: "prometheus-monitor.{{ params.your_domain }}"
    private: "private-monitor.{{ params.your_domain }}"
    theia: "files-monitor.{{ params.your_domain }}"
    minio_gateway: "s3-monitor.{{ params.your_domain }}"
  dns_service_params_list:
    - record: "monitor"
    - record: "prometheus-monitor"
    - record: "private-monitor"
    - record: "files-monitor"
    - record: "s3-monitor"
  dns_prometheus_params_list:
    - record: "prometheus"
  digital_ocean_node_region: "ams3"
  digital_ocean_node_size: "s-1vcpu-1gb"
  certbot_email: "{{ params.certbot_email }}"
  backup_bucket_name: "{{ params.backup_bucket_name }}"
  meta:
    ignore_validators: false
    skip_local_node_preparation: false
    skip_local_pod_preparation: false
    template_no_empty_lines: true
  run_nameserver_main: false
  run_dns_main: false
  use_pod_prefix: true
  use_secrets: false
  use_nginx: true
  use_grafana: true
  use_cadvisor: true
  use_theia: true
  use_minio_gateway: true
  use_s3: true
  use_fluentd: true
  use_certbot: true
  use_private_path: true
  use_basic_auth_private: true
  use_ssl: false
  use_secure_elasticsearch: false
  use_node_exporter: true
  use_internal_node_exporter: true
  use_pod_full_prefix: true
  db_backup_use_s3: false
  define_cron: true
  include_cron_watch: true
  define_s3_backup_lifecycle: true
  enable_logs_backup: true
  enable_logs_setup: true
  enable_sync_backup: true
  enable_sync_setup: true
  enable_backup_replica: false
  prometheus_external_port: "9090"
  inner_scripts_dir: ""
  named_volumes: false
  fluentd_output_plugin: "file"
  s3_cli: "awscli"
  auth_file: "demo/auth/.htpasswd"
  internal_ssl:
    fullchain: "demo/ssl/internal.bundle.crt"
    cert: "demo/ssl/internal.crt"
    ca: "demo/ssl/internal.ca.crt"
    privkey: "demo/ssl/internal.key"
  host_ssh_public_keys_content:
    origin: "env"
    file: "demo/ssh/id_rsa.pub"
  memory_app:
    nginx: 512mb
    grafana: 512mb
    prometheus: 1gb
    node_exporter: 512mb
    cadvisor: 512mb
    theia: 512mb
    minio_gateway: 512mb
    toolbox: 512mb
    fluentd: 256mb
    certbot: 256mb
    logrotator: 256mb
    s3_cli: 512mb
credentials:
  grafana:
    security_admin_password: "123456"
    server_domain: "monitor.{{ params.your_domain }}"
    smtp_enabled: true
    smtp_host: "smtp.sendgrid.net:587"
    smtp_user: "apikey"
    smtp_password: "{{ params.sender_email }}"
    smtp_from_address: "noreply@monitor.{{ params.your_domain }}"
  host:
    host_user: "host"
    host_pass: "111222"
    ssh_file: "demo/ssh/id_rsa"
  digital_ocean:
    api_token: "{{ params.digital_ocean_api_token }}"
  cloudflare:
    email: "{{ params.cloudflare_email }}"
    token: "{{ params.cloudflare_token }}"
  s3:
    endpoint: "{{ params.s3_endpoint }}"
    access_key: "{{ params.s3_access_key }}"
    secret_key: "{{ params.s3_secret_key }}"
  minio_gateway:
    endpoint: "{{ params.minio_gateway_endpoint }}"
    access_key: "{{ params.minio_gateway_access_key }}"
    secret_key: "{{ params.minio_gateway_secret_key }}"
