name: "{{ project_name }}-prometheus"
ctxs: ["local"]
env:
  repo:
    src: "https://github.com/lucasbasquerotto/env-base.git"
    version: "master"
  repo_dir: "env-base"
  file: "examples/prometheus.yml"
env_params:
  private_ips: []
  cloud_name: "digital_ocean"
  domain: "lucasbasquerotto.com"
  prometheus_dns_name: "godaddy"
  prometheus_dns_record: "prometheus-monitor"
  prometheus_full_domain: "prometheus-monitor.lucasbasquerotto.com"
  grafana_dns_name: "godaddy"
  grafana_dns_record: "monitor"
  grafana_full_domain: "monitor.lucasbasquerotto.com"
  theia_dns_name: "godaddy"
  theia_dns_record: "files-monitor"
  theia_full_domain: "files-monitor.lucasbasquerotto.com"
  filestash_dns_name: "godaddy"
  filestash_dns_record: "s3-monitor"
  filestash_full_domain: "s3-monitor.lucasbasquerotto.com"
  minio_gateway_dns_name: "godaddy"
  minio_gateway_dns_record: "s3-monitor"
  minio_gateway_full_domain: "s3-monitor.lucasbasquerotto.com"
  certbot_domains: >-
    monitor.lucasbasquerotto.com
    prometheus-monitor.lucasbasquerotto.com
    files-monitor.lucasbasquerotto.com
    s3-monitor.lucasbasquerotto.com
  pod_custom_dir_sync: "{{ params.pod_custom_dir_sync | default(false) }}"
  use_pod_prefix: true
  db_backup_use_s3: false
  restore_db: false
  use_node_exporter: true
  use_cadvisor: true
  use_theia: true
  use_minio_gateway: true
  use_filestash: false
  use_fluentd: true
  use_certbot: true
  ssl: true
  use_pod_full_prefix: true
  s3_cli: "awscli"
  certbot_email: "lucasbasquerotto@gmail.com"
  auth_file: "{{ params.env_dir }}/.htpasswd"
  fluentd_output_plugin: "elasticsearch"
  backup_bucket_name: "lucasbasquerotto-prometheus-backup"
  backup_replica_bucket_name: "lucasbasquerotto-prometheus-replica-backup"
  snapshot_name: "snapshot-20200813-230131"
  db_setup_restore_remote_file: "https://github.com/lucasbasquerotto/backups/blob/master/prometheus/db/20200813_230132.zip?raw=true"
  named_volumes: "{{ params.named_volumes | default(false) }}"
  local_custom_ssl:
    main_domain: "localhost"
    fullchain: "{{ params.env_dir }}/ssl/bundle.crt"
    privkey: "{{ params.env_dir }}/ssl/localhost.key"
  host_ssh_public_keys_content:
    origin: "env"
    file: "{{ params.env_dir }}/ssh/host.pub"
credentials:
  digital_ocean:
    api_token: "<api_token>"
  backup_bucket:
    host: "<host>"
    ssl: true
    endpoint: "<endpoint>"
    access_key: "<api_token>"
    secret_key: "<secret_key>"
  backup_replica_bucket:
    host: "<host>"
    ssl: true
    endpoint: "<endpoint>"
    access_key: "<api_token>"
    secret_key: "<secret_key>"
  minio_gateway:
    host: "<host>"
    ssl: true
    endpoint: "<endpoint>"
    access_key: "<api_token>"
    secret_key: "<secret_key>"
  godaddy:
    api_server: "https://api.godaddy.com"
    api_version: "1"
    api_key: "<api_key>"
    api_secret: "<api_secret>"
  host:
    host_user: "host"
    host_pass: "111222"
    ssh_encrypted_key_path_rel: "{{ params.env_dir }}/ssh/host.encrypted.key"
  localhost:
    host_user: "root"
  grafana:
    security_admin_password: "MYPASSWORT"
    server_domain: "myrul.com"
    smtp_enabled: "true"
    smtp_host: "smtp.gmail.com:587"
    smtp_user: "myaddress@gmail.com"
    smtp_password: "mypassword"
    smtp_from_address: "myaddress@gmail.com"
