#!/bin/bash
# ./build
docker run -it --rm -v "$(pwd)"/data:/main -v "$(pwd)"/env:/env local/demo

# sudo docker run --rm -it -v /lrd:/test --workdir "/test" local/cloud:1.3.5 /bin/bash
# cd /test
# echo 'exec "${@}"' > /usr/local/bin/sudo
# chmod +x /usr/local/bin/sudo

# ./ctl/run l -id mediawiki-local