#!/bin/bash
# ./build
docker run -it --rm -v "$(pwd)"/data:/main -v "$(pwd)"/env:/env local/demo

# sudo docker run --rm -it -v /lrd:/test --workdir "/test" lucasbasquerotto/cloud:1.3.5 /bin/bash
# ./ctl/run l -id mediawiki-local