name: "{{ params.name }}"
ctxs: "{{ params.ctxs }}"
meta:
  template_no_empty_lines: true
  skip_local_node_preparation: false
  skip_local_pod_preparation: false
cloud:
  repo: "cloud"
  ext_repos:
    - repo: "ext_cloud"
      dir: "ext-cloud"
  collections:
    - namespace: "lrd"
      collection: "ext_cloud"
      path: "ext-cloud/collection"
  hosts:
    type: "template"
    file: "files/hosts.tpl.ini"
    schema: "files/hosts.schema.yml"
main:
  remote:
    extend_cloud: true
    initial_services:
      - "{{ params.env_params.cloud_service }}"
      - "{{ params.env_params.discourse.use_s3 | default(false) | bool | ternary('s3_buckets', 'skip') }}"
    nodes:
      - name: "app"
        key: "discourse"
        can_destroy: true
        params:
          dns_service_params_list: "{{ params.env_params.dns_service_params_list | default([]) }}"
        pods:
          discourse:
            transfer:
              - dest: "containers/app.yml"
                src: >-
                  {{
                    params.env_params.discourse_app_container_content
                    | default({ 'type': 'env', 'name': 'discourse_app_container' })
                  }}
    run_stages:
      - tasks:
          - name: "discourse_setup"
            all_nodes: true
            task_target: "pod"
          - name: "discourse_rebuild"
            all_nodes: true
            task_target: "pod"
  multicontainer:
    extend_cloud: true
    initial_services:
      - "{{ params.env_params.cloud_service }}"
      - "{{ params.env_params.discourse.use_s3 | default(false) | bool | ternary('s3_buckets', 'skip') }}"
    nodes:
      - name: "app"
        key: "discourse"
        can_destroy: true
        params:
          dns_service_params_list: "{{ params.env_params.dns_service_params_list | default([]) }}"
        pods:
          discourse:
            transfer:
              - dest: "containers/web.yml"
                src: >-
                  {{
                    params.env_params.discourse_web_internal_container_content
                    | default({ 'type': 'env', 'name': 'discourse_web_internal_container' })
                  }}
              - dest: "containers/db.yml"
                src: >-
                  {{
                    params.env_params.discourse_db_internal_container_content
                    | default({ 'type': 'env', 'name': 'discourse_db_internal_container' })
                  }}
    run_stages:
      - tasks:
          - name: "discourse_setup"
            all_nodes: true
            task_target: "pod"
          - name: "discourse_rebuild_db"
            all_nodes: true
            task_target: "pod"
      - tasks:
          - name: "discourse_rebuild_web"
            all_nodes: true
            task_target: "pod"
  nodes:
    extend_cloud: true
    initial_services:
      - "{{ params.env_params.cloud_service }}"
      - "{{ params.env_params.discourse.use_s3 | default(false) | bool | ternary('s3_buckets', 'skip') }}"
    nodes:
      - name: "web"
        key: "discourse"
        can_destroy: true
        dependencies:
          db:
            type: "node"
            host: "db"
            port: "5432"
            required_amount: 1
          redis:
            type: "node"
            host: "redis"
            port: "6379"
            required_amount: 1
        params:
          service_params:
            tags:
              - "auto"
              - "discourse-web"
              - "discourse-dmz"
          dns_service_params_list: "{{ params.env_params.dns_service_params_list | default([]) }}"
        pods:
          discourse:
            transfer:
              - dest: "containers/web.yml"
                src: >-
                  {{
                    params.env_params.discourse_web_container_content
                    | default({ 'type': 'env', 'name': 'discourse_web_container' })
                  }}
      - name: "redis"
        key: "discourse"
        can_destroy: true
        params:
          service_params:
            tags:
              - "auto"
              - "discourse-redis"
        pods:
          discourse:
            transfer:
              - dest: "containers/redis.yml"
                src: >-
                  {{
                    params.env_params.discourse_redis_container_content
                    | default({ 'type': 'env', 'name': 'discourse_redis_container' })
                  }}
      - name: "db"
        key: "discourse"
        can_destroy: true
        params:
          service_params:
            tags:
              - "auto"
              - "discourse-pg"
        pods:
          discourse:
            transfer:
              - dest: "containers/db.yml"
                src: >-
                  {{
                    params.env_params.discourse_db_container_content
                    | default({ 'type': 'env', 'name': 'discourse_db_container' })
                  }}
    run_stages:
      - tasks:
          - name: "discourse_setup"
            all_nodes: true
            task_target: "pod"
          - name: "discourse_rebuild_db"
            nodes: ["db"]
            task_target: "pod"
          - name: "discourse_rebuild_redis"
            nodes: ["redis"]
            task_target: "pod"
      - tasks:
          # - name: "task_dependencies"
          #   nodes: ["web"]
          #   task_target: "node"
          - name: "discourse_rebuild_web"
            nodes: ["web"]
            task_target: "pod"
services:
  skip:
    list: true
    services: []
  s3_buckets:
    base_dir: "ext-cloud"
    namespace: "ext_s3"
    task: "tasks/s3/main.s3.yml"
    schema: "tasks/s3/schema.s3.yml"
    validator: "tasks/s3/validator.s3.yml"
    credentials:
      s3: "discourse_s3"
    params:
      list:
        - bucket: "{{ params.env_params.discourse.backup_bucket_name | default('') }}"
          permission: "private"
        - bucket: "{{ params.env_params.discourse.uploads_bucket_name | default('') }}"
          permission: "public-read"
  node_dns_service:
    base_dir: "ext-cloud"
    namespace: "ext_dns"
    task: >-
      tasks/dns/{{
        params.env_params.dns_provider | default('')
      }}/{{
        params.env_params.dns_provider | default('')
      }}.main.dns.yml
    schema: >-
      tasks/dns/{{
        params.env_params.dns_provider | default('')
      }}/{{
        params.env_params.dns_provider | default('')
      }}.schema.dns.yml
    validator: >-
      tasks/dns/{{
        params.env_params.dns_provider | default('')
      }}/{{
        params.env_params.dns_provider | default('')
      }}.validator.dns.yml
    credentials:
      dns: "{{ params.env_params.dns_provider }}"
    params:
      zone: "{{ params.env_params.main_domain }}"
  digital_ocean_vpn:
    base_dir: "ext-cloud"
    namespace: "ext_vpn"
    task: "tasks/vpn/digital_ocean/digital_ocean.main.vpn.yml"
    schema: "tasks/vpn/digital_ocean/digital_ocean.schema.vpn.yml"
    validator: "tasks/vpn/digital_ocean/digital_ocean.validator.vpn.yml"
    credentials:
      vpn: "digital_ocean"
    params:
      tags:
        - "auto"
        - "discourse-pg"
        - "discourse-redis"
        - "discourse-web"
        - "discourse-dmz"
      firewalls:
        - name: "auto"
          tags: ["auto"]
          inbound_rules:
            - ports: "22"
              sources:
                tags: ["main"]
                addresses: "{{ params.env_params.private_ips }}"
          outbound_rules:
            - protocol: "tcp"
              ports: "1-65535"
              destinations:
                addresses: ["0.0.0.0/0", "::/0"]
            - protocol: "udp"
              ports: "1-65535"
              destinations:
                addresses: ["0.0.0.0/0", "::/0"]
            - protocol: "icmp"
              ports: "1-65535"
              destinations:
                addresses: ["0.0.0.0/0", "::/0"]
        - name: "discourse-pg"
          tags: ["discourse-pg"]
          inbound_rules:
            - ports: "5432"
              sources:
                tags: ["discourse-web"]
        - name: "discourse-redis"
          tags: ["discourse-redis"]
          inbound_rules:
            - ports: "6379"
              sources:
                tags: ["discourse-web"]
        - name: "discourse-web"
          tags: ["discourse-web"]
          inbound_rules:
            - ports: "80"
              sources:
                tags: ["discourse-dmz"]
            - ports: "443"
              sources:
                tags: ["discourse-dmz"]
        - name: "discourse-dmz"
          tags: ["discourse-dmz"]
          inbound_rules:
            - ports: "80"
              sources:
                addresses: ["0.0.0.0/0", "::/0"]
            - ports: "443"
              sources:
                addresses: ["0.0.0.0/0", "::/0"]
  digital_ocean_node:
    base_dir: "ext-cloud"
    namespace: "ext_node"
    task: "tasks/node/digital_ocean/digital_ocean.main.node.yml"
    schema: "tasks/node/digital_ocean/digital_ocean.schema.node.yml"
    validator: "tasks/node/digital_ocean/digital_ocean.validator.node.yml"
    credentials:
      node: "digital_ocean"
    params:
      image_id: "ubuntu-18-04-x64"
      ipv6: true
      region_id: "ams3"
      size_id: "s-1vcpu-1gb"
    contents:
      user_data:
        type: "template"
        origin: "cloud"
        file: "ext-cloud/files/user-data/ubuntu-18.04.tpl.sh"
        schema: "ext-cloud/files/user-data/ubuntu-18.04.schema.yml"
        params:
          user_directories: ["/var/discourse", "/var/cloud"]
          install_docker: true
          install_podman: false
          install_packages: false
        credentials:
          node: "host"
        contents:
          host_ssh_public_keys: "{{ params.env_params.host_ssh_public_keys_content | default('') }}"
  linode:
    base_dir: "ext-cloud"
    namespace: "ext_node"
    task: "tasks/node/linode/linode.main.node.yml"
    schema: "tasks/node/linode/linode.schema.node.yml"
    validator: "tasks/node/linode/linode.validator.node.yml"
    credentials:
      node: "linode"
    params:
      image: "linode/ubuntu18.04"
      region: "us-east"
      type: "g6-standard-1"
    contents:
      user_data:
        type: "template"
        origin: "cloud"
        file: "ext-cloud/files/user-data/ubuntu-18.04.tpl.sh"
        schema: "ext-cloud/files/user-data/ubuntu-18.04.schema.yml"
        params:
          user_directories: ["/var/cloud"]
          install_docker: true
          install_podman: false
          install_packages: false
        credentials:
          node: "host"
        contents:
          host_ssh_public_keys: "{{ params.env_params.host_ssh_public_keys_content | default('') }}"
  linode:
    base_dir: "ext-cloud"
    namespace: "ext_node"
    task: "tasks/node/linode/linode.main.node.yml"
    schema: "tasks/node/linode/linode.schema.node.yml"
    validator: "tasks/node/linode/linode.validator.node.yml"
    credentials:
      node: "linode"
    params:
      image: "linode/ubuntu18.04"
      region: "us-east"
      type: "g6-standard-1"
    contents:
      user_data:
        type: "template"
        origin: "cloud"
        file: "ext-cloud/files/user-data/ubuntu-18.04.tpl.sh"
        schema: "ext-cloud/files/user-data/ubuntu-18.04.schema.yml"
        params:
          user_directories: ["/var/cloud"]
          install_docker: true
          install_podman: false
          install_packages: false
        credentials:
          node: "host"
        contents:
          host_ssh_public_keys: "{{ params.env_params.host_ssh_public_keys_content | default('') }}"
nodes:
  discourse:
    service:
      name: "{{ params.env_params.node_service }}"
      params:
        tags:
          - "auto"
          - "discourse-dmz"
    dns_service: "node_dns_service"
    base_dir: "/var/cloud"
    root: true
    credentials:
      host: "host"
    params:
      host_users:
        - name: "host"
          setup_log_file: "/var/log/setup.log"
          setup_finished_log_regex: "^Setup Finished.*$"
          setup_success_log_last_line: "Setup Finished - Success"
          initial_connection_timeout: 90
          setup_finished_timeout: 300
    pods: ["discourse"]
pods:
  discourse:
    repo: "discourse_docker"
    base_dir: "/var/discourse"
    flat: true
    root: "yes"
    fast_prepare: "true"
    transfer:
      - dest: "shared/bin/setup"
        executable: true
        src:
          origin: "cloud"
          file: "ext-cloud/files/discourse/discourse-setup.sh"
tasks:
  task_dependencies:
    type: "task"
    file: "tasks/run/dependencies.yml"
    schema: "tasks/run/dependencies.schema.yml"
    params:
      timeout: 5
  discourse_setup:
    type: "shell"
    root: true
    cmd: "./shared/bin/setup"
  discourse_rebuild:
    type: "shell"
    root: true
    cmd: "./launcher rebuild app"
  discourse_rebuild_db:
    type: "shell"
    root: true
    cmd: "./launcher rebuild db"
  discourse_rebuild_redis:
    type: "shell"
    root: true
    cmd: "./launcher rebuild redis"
  discourse_rebuild_web:
    type: "shell"
    root: true
    cmd: "./launcher rebuild web"
contents:
  discourse_app_container:
    type: "env"
    name: "discourse_container"
    params:
      type: "app"
  discourse_web_internal_container:
    type: "env"
    name: "discourse_container"
    params:
      type: "web"
      internal_redis: true
      db_same_host: true
  discourse_db_internal_container:
    type: "env"
    name: "discourse_container"
    params:
      type: "db"
      db_same_host: true
  discourse_web_container:
    type: "env"
    name: "discourse_container"
    params:
      type: "web"
  discourse_db_container:
    type: "env"
    name: "discourse_container"
    params:
      type: "db"
  discourse_redis_container:
    type: "env"
    name: "discourse_container"
    params:
      type: "redis"
  discourse_container:
    type: "template"
    origin: "cloud"
    file: "ext-cloud/files/discourse/container.tpl.yml"
    shared_params: ["discourse_params"]
    credentials:
      db: "db"
      discourse_smtp: "discourse_smtp"
      discourse_s3: "discourse_s3"
content_shared_params:
  discourse_params: "{{ params.env_params.discourse | default({}) }}"
repos:
  cloud:
    src: "https://github.com/lucasbasquerotto/cloud.git"
    version: "master"
  ext_cloud:
    src: "https://github.com/lucasbasquerotto/ext-cloud.git"
    version: "master"
  discourse_docker:
    src: "https://github.com/discourse/discourse_docker.git"
    version: "master"
credentials: "{{ params.credentials | default({}) }}"
