name: "{{ project_name }}"
ctxs: "{{ project_ctxs }}"
migration: ""
container: ""
meta:
  ignore_validators: false
  skip_local_pod_preparation: false
  template_no_empty_lines: true
cloud:
  repo: "cloud"
  ext_repos:
    - repo: "ext_cloud"
      dir: "ext-cloud"
  collections:
    - namespace: "lrd"
      collection: "ext_cloud"
      path: "ext-cloud/collection"
  hosts:
    type: "template"
    file: "files/hosts.tpl.ini"
    schema: "files/hosts.schema.yml"
main:
  cloud:
    extend_cloud: true
    initial_services:
      - "{{ params.cloud_service | default('skip') }}"
      - "{{ params.run_dns_main | default(false) | bool | ternary('dns_main_service', 'skip') }}"
  s3_replica_buckets:
    extend_cloud: true
    initial_services:
      - name: "s3_buckets"
        can_destroy: true
      - name: "s3_replica_buckets"
        can_destroy: true
  local:
    extend_cloud: true
    nodes:
      - name: "app"
        key: "efk_local"
        local: true
  remote:
    extend_cloud: true
    initial_services:
      - "{{ params.cloud_service | default('skip') }}"
      - "{{ params.run_dns_main | default(false) | bool | ternary('dns_main_service', 'skip') }}"
      - name: "s3_buckets"
        can_destroy: true
    nodes:
      - name: "app"
        key: "efk"
        can_destroy: true
    run_stages:
      - tasks:
          - name: "docker_compose_install"
            all_nodes: true
            task_target: "node"
          - name: "main_upgrade"
            all_nodes: true
            task_target: "pod"
  nodes:
    extend_cloud: true
    initial_services:
      - "{{ params.cloud_service | default('skip') }}"
      - "{{ params.run_dns_main | default(false) | bool | ternary('dns_main_service', 'skip') }}"
      - name: "s3_buckets"
        can_destroy: true
    nodes:
      - name: "db"
        key: "efk"
        can_destroy: true
        params:
          service_params:
            tags:
              - "auto"
              - "elasticsearch"
        pods:
          efk:
            params:
              type: "db"
            group_params:
              memory: "memory_db"
      - name: "web"
        key: "efk"
        can_destroy: true
        dependencies:
          elasticsearch:
            type: "node"
            host: "db"
            port: "9200"
        params:
          service_params:
            tags:
              - "auto"
              - "efk-web"
              - "efk-dmz"
        pods:
          efk:
            params:
              type: "web"
            group_params:
              memory: "memory_web"
    run_stages:
      - tasks:
          - name: "docker_compose_install"
            all_nodes: true
            task_target: "node"
          - name: "main_build"
            all_nodes: true
            task_target: "pod"
          - name: "main_upgrade"
            nodes: ["db"]
            task_target: "pod"
      - tasks:
          - name: "main_upgrade"
            nodes: ["web"]
            task_target: "pod"
services:
  skip:
    list: true
    services: []
  s3_buckets:
    base_dir: "ext-cloud"
    namespace: "ext_s3"
    task: "tasks/s3/main.s3.yml"
    schema: "tasks/s3/schema.s3.yml"
    validator: "tasks/s3/validator.s3.yml"
    credentials:
      s3: "s3"
    params:
      list:
        - bucket: "{{ params.backup_bucket_name | default('') }}"
          permission: "private"
  s3_replica_buckets:
    base_dir: "ext-cloud"
    namespace: "ext_s3"
    task: "tasks/s3/main.s3.yml"
    schema: "tasks/s3/schema.s3.yml"
    validator: "tasks/s3/validator.s3.yml"
    credentials:
      s3: "s3"
    params:
      list:
        - bucket: "{{ params.backup_replica_bucket_name | default('') }}"
          permission: "private"
  dns_main_service:
    list: true
    services:
      - name: "dns_base_service"
        params:
          list: "{{ params.dns_main_service_params_list | default([]) }}"
  dns_base_service:
    base_dir: "ext-cloud"
    namespace: "ext_dns"
    task: >-
      tasks/dns/{{
        params.dns_provider | default('')
      }}/{{
        params.dns_provider | default('')
      }}.main.dns.yml
    schema: >-
      tasks/dns/{{
        params.dns_provider | default('')
      }}/{{
        params.dns_provider | default('')
      }}.schema.dns.yml
    validator: >-
      tasks/dns/{{
        params.dns_provider | default('')
      }}/{{
        params.dns_provider | default('')
      }}.validator.dns.yml
    credentials:
      dns: "{{ params.dns_provider | default('') }}"
    params:
      zone: "{{ params.main_domain | default('') }}"
  digital_ocean_vpn:
    base_dir: "ext-cloud"
    namespace: "ext_vpn"
    task: "tasks/vpn/digital_ocean/digital_ocean.main.vpn.yml"
    schema: "tasks/vpn/digital_ocean/digital_ocean.schema.vpn.yml"
    validator: "tasks/vpn/digital_ocean/digital_ocean.validator.vpn.yml"
    credentials:
      vpn: "digital_ocean"
    params:
      tags:
        - "auto"
        - "elasticsearch"
        - "efk-web"
        - "efk-dmz"
      firewalls:
        - name: "private"
          tags: ["auto"]
          inbound_rules:
            - ports: "9080"
              sources:
                addresses: "{{ params.private_ips | default([]) }}"
            - ports: "9443"
              sources:
                addresses: "{{ params.private_ips | default([]) }}"
        - name: "auto"
          tags: ["auto"]
          inbound_rules:
            - ports: "22"
              sources:
                tags: ["main"]
                addresses: "{{ params.private_ips | default([]) }}"
          outbound_rules:
            - protocol: "tcp"
              ports: "1-65535"
              destinations:
                addresses: ["0.0.0.0/0", "::/0"]
            - protocol: "udp"
              ports: "1-65535"
              destinations:
                addresses: ["0.0.0.0/0", "::/0"]
            - protocol: "icmp"
              ports: "1-65535"
              destinations:
                addresses: ["0.0.0.0/0", "::/0"]
        - name: "elasticsearch"
          tags: ["elasticsearch"]
          inbound_rules:
            - ports: "9200"
              sources:
                tags: ["auto", "efk-web"]
        - name: "efk-web"
          tags: ["efk-web"]
          inbound_rules:
            - ports: "80"
              sources:
                tags: ["efk-dmz"]
            - ports: "443"
              sources:
                tags: ["efk-dmz"]
        - name: "efk-dmz"
          tags: ["efk-dmz"]
          inbound_rules:
            - ports: "80"
              sources:
                addresses: ["0.0.0.0/0", "::/0"]
            - ports: "443"
              sources:
                addresses: ["0.0.0.0/0", "::/0"]
  digital_ocean_node:
    base_dir: "ext-cloud"
    namespace: "ext_node"
    task: "tasks/node/digital_ocean/digital_ocean.main.node.yml"
    schema: "tasks/node/digital_ocean/digital_ocean.schema.node.yml"
    validator: "tasks/node/digital_ocean/digital_ocean.validator.node.yml"
    credentials:
      node: "digital_ocean"
    params:
      image_id: "ubuntu-18-04-x64"
      ipv6: true
      region_id: "ams3"
      size_id: "s-2vcpu-2gb"
    contents:
      user_data:
        type: "env"
        name: "user_data_ubuntu"
  linode:
    base_dir: "ext-cloud"
    namespace: "ext_node"
    task: "tasks/node/linode/linode.main.node.yml"
    schema: "tasks/node/linode/linode.schema.node.yml"
    validator: "tasks/node/linode/linode.validator.node.yml"
    credentials:
      node: "linode"
    params:
      image: "linode/ubuntu18.04"
      region: "us-east"
      type: "g6-standard-1"
    contents:
      user_data:
        type: "env"
        name: "user_data_ubuntu"
nodes:
  efk_local:
    credentials:
      host: "localhost"
    pods:
      - name: "efk"
        params:
          local: true
          local_standard_ports: "{{ params.local_standard_ports | default(false) }}"
          named_volumes: "{{ params.named_volumes | default(false) }}"
          custom_ssl: "{{ params.local_custom_ssl | default({}) }}"
          internal_ssl: "{{ params.internal_ssl | default({}) }}"
          enable_logs_setup: false
          enable_sync_setup: false
          main_domain: "{{ params.local_main_domain | default('localhost') }}"
          domains: "{{ params.local_domains | default({}) }}"
  efk:
    service:
      name: "{{ params.node_service | default('skip') }}"
      params:
        tags:
          - "auto"
          - "efk-dmz"
    dns_service: "dns_base_service"
    base_dir: "/var/cloud"
    root: true
    credentials:
      host: "host"
    params:
      dns_service_params_list: "{{ params.dns_service_params_list | default([]) }}"
      host_users:
        - name: "host"
          setup_log_file: "/var/log/setup.log"
          setup_finished_log_regex: "^Setup Finished.*$"
          setup_success_log_last_line: "Setup Finished - Success"
          initial_connection_timeout: 90
          setup_finished_timeout: 300
    pods:
      - name: "efk"
        params:
          local: false
          domains: "{{ params.domains | default({}) }}"
pods:
  efk:
    repo: "pod"
    root: "yes"
    ctx: "ext-pod/efk/efk.ctx.yml"
    schema: "ext-pod/efk/efk.schema.yml"
    validator: "ext-pod/efk/efk.validator.yml"
    fast_prepare: "true"
    ext_repos:
      - repo: "ext_pod"
        dir: "ext-pod"
    credentials:
      elasticsearch: "elasticsearch"
      minio_gateway: "{{ params.use_minio_gateway | default(false) | bool | ternary('minio_gateway', '') }}"
      backup_bucket: "{{ params.use_s3 | default(false) | bool | ternary('s3', '') }}"
      backup_replica_bucket: "{{ params.enable_backup_replica | default(false) | bool | ternary('s3_replica', '') }}"
    params:
      type: "app"
      orchestration: "docker_compose"
      custom_dir: "ext-pod"
      custom_dir_sync: "{{ params.pod_custom_dir_sync | default(false) }}"
      meta: "{{ params.pod_meta | default({}) }}"
      main_domain: "{{ params.main_domain | default('') }}"
      use_secrets: "{{ params.use_secrets | default(false) }}"
      use_ssl: "{{ params.use_ssl | default(false) }}"
      use_secure_elasticsearch: "{{ params.use_secure_elasticsearch | default(false) }}"
      use_pod_prefix: "{{ params.use_pod_prefix | default(false) }}"
      use_pod_full_prefix: "{{ params.use_pod_full_prefix | default(false) }}"
      use_nginx: "{{ params.use_nginx | default(true) }}"
      use_theia: "{{ params.use_theia | default(false) }}"
      use_minio_gateway: "{{ params.use_minio_gateway | default(false) }}"
      use_filestash: "{{ params.use_filestash | default(false) }}"
      use_s3: "{{ params.use_s3 | default(false) }}"
      use_local_s3: "{{ params.use_local_s3 | default(false) }}"
      use_fluentd: "{{ params.use_fluentd | default(false) }}"
      use_certbot: "{{ params.use_certbot | default(false) }}"
      use_private_path: "{{ params.use_private_path | default(false) }}"
      auth_file: "{{ params.auth_file | default('') }}"
      s3_cli: "{{ params.s3_cli | default('') }}"
      define_s3_backup_lifecycle: "{{ params.define_s3_backup_lifecycle | default(false) }}"
      s3_backup_lifecycle_file: "s3-backup-lifecycle.json"
      define_cron: "{{ params.define_cron | default(false) }}"
      include_cron_watch: "{{ params.include_cron_watch | default(false) }}"
      cron_src: "env/cron/cron-file"
      cron_dest: "/var/spool/cron/crontabs/root"
      backup_bucket_name: "{{ params.backup_bucket_name | default('') }}"
      backup_bucket_path: "{{ params.backup_bucket_path | default('') }}"
      backup_replica_bucket_name: "{{ params.backup_replica_bucket_name | default('') }}"
      backup_replica_bucket_path: "{{ params.backup_replica_bucket_path | default('') }}"
      restore_db: "{{ params.restore_db | default(false) }}"
      enable_db_backup: "{{ params.enable_db_backup | default(false) }}"
      enable_db_setup: "{{ params.enable_db_setup | default(false) }}"
      enable_logs_backup: "{{ params.enable_logs_backup | default(false) }}"
      enable_logs_setup: "{{ params.enable_logs_setup | default(false) }}"
      enable_sync_backup: "{{ params.enable_sync_backup | default(false) }}"
      enable_sync_setup: "{{ params.enable_sync_setup | default(false) }}"
      enable_backup_replica: "{{ params.enable_backup_replica | default(false) }}"
      db_backup:
        s3_snapshot: "{{ params.db_backup_s3_snapshot | default(false) }}"
        is_compressed_file: "{{ not (params.db_backup_s3_snapshot | default(false) | bool) }}"
        backup_bucket_sync_dir: "db"
      db_setup:
        use_s3: "{{ params.db_setup_use_s3 | default(false) }}"
        snapshot_name: "{{ params.snapshot_name | default('') }}"
        restore_remote_file: "{{ params.db_setup_restore_remote_file | default('') }}"
      certbot:
        email: "{{ params.certbot_email | default('') }}"
        staging: "{{ params.certbot_staging | default(false) }}"
        force: "{{ params.certbot_force | default(false) }}"
      services:
        fluentd:
          port: "24224"
          output_plugin: "{{ params.fluentd_output_plugin | default('file') }}"
        elasticsearch:
          port: "9200"
          java_opts: "-Xms700m -Xmx700m"
        kibana:
          port: "5601"
      images:
        nginx_image: "nginx"
        nginx_version: "1.14.2-alpine"
        elasticsearch_image: "docker.elastic.co/elasticsearch/elasticsearch"
        elasticsearch_version: "7.5.0"
        kibana_image: "docker.elastic.co/kibana/kibana"
        kibana_version: "7.5.0"
        theia_image: "theiaide/theia"
        theia_version: "1.3.0"
        minio_gateway_image: "minio/minio"
        minio_gateway_version: "RELEASE.2020-07-02T00-15-09Z"
        minio_image: "minio/minio"
        minio_version: "RELEASE.2021-03-17T02-33-02Z"
        filestash_image: "machines/filestash"
        filestash_version: "4cbeb2c"
        toolbox_image: "lucasbasquerotto/image"
        toolbox_version: "toolbox-20200715-02"
        certbot_image: "certbot/certbot"
        certbot_version: "v1.2.0"
        awscli_image: "lucasbasquerotto/aws-cli"
        awscli_version: "1.0.0"
        mc_image: "minio/mc"
        mc_version: "RELEASE.2021-03-12T03-36-59Z"
        rclone_image: "rclone/rclone"
        rclone_version: "1.54.0"
        logrotator_image: "python"
        logrotator_version: "3.8.4-buster"
        fluentd_image: "lucasbasquerotto/image"
        fluentd_version: "fluentd-20200617"
    group_params:
      memory: "memory_app"
    transfer:
      - dest: "env/cron/cron-file"
        when: "{{ params.define_cron | default(false) }}"
        src:
          type: "template"
          origin: "cloud"
          file: "ext-cloud/files/cron/pod.tpl.sh"
          schema: "ext-cloud/files/cron/pod.schema.yml"
          params:
            tasks:
              - name: "watch"
                when: "{{ params.include_cron_watch | default(false) }}"
                task: "unique:action:watch"
                cron: "*/1 * * * *"
              - name: "pending"
                when: "{{ not (params.include_cron_watch | default(false) | bool) }}"
                task: "unique:action:pending"
                cron: "*/1 * * * *"
              - name: "log"
                task: "custom:unique:log"
                cron: "*/5 * * * *"
              - name: "block_ips"
                when: "{{ params.block_ips | default(false) }}"
                task: "unique:action:block_ips"
                cron: "*/15 * * * *"
              - name: "full_log"
                task: "unique:all logrotate log_summary"
                cron: "* */1 * * *"
              - name: "backup"
                task: "unique:action:backup"
                cron: "0 */6 * * *"
              - name: "replicate_s3"
                task: "unique:action:replicate_s3"
                cron: "3 */1 * * *"
      - dest: "env/{{ params.s3_cli | default('') }}/etc/s3-backup-lifecycle.json"
        when: "{{ params.define_s3_backup_lifecycle | default(false) | bool }}"
        src:
          type: "template"
          origin: "cloud"
          file: "ext-cloud/files/s3/s3_lifecycle.json.j2"
          schema: "ext-cloud/files/s3/s3_lifecycle.schema.yml"
          params:
            rules:
              - name: "logs-expiration"
                filter_prefix: "logs/"
                expiration_days: 30
                older_versions_expiration_days: 180
pod_group_params:
  memory_app:
    nginx: 512mb
    kibana: 512mb
    elasticsearch: 1gb
    theia: 512mb
    minio_gateway: 512mb
    filestash: 512mb
    toolbox: 512mb
    certbot: 256mb
    fluentd: 256mb
    s3_cli: 512mb
  memory_db:
    elasticsearch: 1gb
    toolbox: 512mb
    fluentd: 256mb
    s3_cli: 512mb
  memory_web:
    nginx: 512mb
    kibana: 512mb
    theia: 512mb
    minio_gateway: 512mb
    filestash: 512mb
    toolbox: 512mb
    certbot: 256mb
    fluentd: 256mb
    s3_cli: 512mb
tasks:
  docker_compose_install:
    type: "task"
    root: true
    file: "ext-cloud/run-tasks/docker.yml"
    schema: "ext-cloud/run-tasks/docker.schema.yml"
    params:
      compose:
        version: "1.27.2"
  main_build:
    type: "shell"
    root: true
    cmd: "./run build"
  main_upgrade:
    type: "shell"
    root: true
    cmd: "./run upgrade"
contents:
  user_data_ubuntu:
    type: "template"
    origin: "cloud"
    file: "ext-cloud/files/user-data/ubuntu-18.04.tpl.sh"
    schema: "ext-cloud/files/user-data/ubuntu-18.04.schema.yml"
    params:
      user_directories: ["/var/cloud"]
      install_docker: true
      install_podman: false
      install_packages: true
    credentials:
      node: "host"
    contents:
      host_ssh_public_keys: "{{ params.host_ssh_public_keys_content | default('') }}"
repos:
  cloud:
    src: "https://github.com/lucasbasquerotto/cloud.git"
    version: "master"
  ext_cloud:
    src: "https://github.com/lucasbasquerotto/ext-cloud.git"
    version: "master"
  pod:
    src: "https://github.com/lucasbasquerotto/pod.git"
    version: "master"
  ext_pod:
    src: "https://github.com/lucasbasquerotto/ext-pod.git"
    version: "master"
credentials: "{{ credentials }}"
