name: "{{ project_name }}"
ctxs: "{{ project_ctxs }}"
migration: ""
container: ""
meta:
  ignore_validators: false
  skip_local_pod_preparation: false
  template_no_empty_lines: true
cloud:
  repo: "cloud"
  ext_repos:
    - repo: "ext_cloud"
      dir: "ext-cloud"
  collections:
    - namespace: "lrd"
      collection: "ext_cloud"
      path: "ext-cloud/collection"
  hosts:
    type: "template"
    file: "files/hosts.tpl.ini"
    schema: "files/hosts.schema.yml"
main:
  cloud:
    extend_cloud: true
    initial_services:
      - "{{ params.cloud_service | default('skip') }}"
  s3_replica_buckets:
    extend_cloud: true
    initial_services:
      - name: "s3_replica_buckets"
        can_destroy: true
  local:
    extend_cloud: true
    nodes:
      - name: "app"
        key: "prometheus_local"
        local: true
  remote:
    extend_cloud: true
    initial_services:
      - "{{ params.cloud_service | default('skip') }}"
      - name: "s3_buckets"
        can_destroy: true
    nodes:
      - name: "app"
        key: "prometheus"
        can_destroy: true
    run_stages:
      - tasks:
          - name: "docker_compose_install"
            all_nodes: true
            task_target: "node"
          - name: "main_upgrade"
            all_nodes: true
            task_target: "pod"
  nodes:
    extend_cloud: true
    initial_services:
      - "{{ params.cloud_service | default('skip') }}"
      - name: "s3_buckets"
        can_destroy: true
    nodes:
      - name: "db"
        key: "prometheus"
        can_destroy: true
        params:
          service_params:
            tags:
              - "auto"
              - "prometheus"
        pods:
          prometheus:
            params:
              type: "db"
              use_nginx: false
            group_params:
              memory: "memory_db"
      - name: "web"
        key: "prometheus"
        can_destroy: true
        dependencies:
          prometheus:
            type: "node"
            host: "db"
            port: "9090"
        params:
          service_params:
            tags:
              - "auto"
              - "prometheus-web"
              - "prometheus-dmz"
        pods:
          prometheus:
            params:
              type: "web"
            group_params:
              memory: "memory_web"
    run_stages:
      - tasks:
          - name: "docker_compose_install"
            all_nodes: true
            task_target: "node"
          - name: "main_build"
            all_nodes: true
            task_target: "pod"
          - name: "main_upgrade"
            nodes: ["db"]
            task_target: "pod"
      - tasks:
          - name: "main_upgrade"
            nodes: ["web"]
            task_target: "pod"
services:
  skip:
    list: true
    services: []
  s3_buckets:
    base_dir: "ext-cloud"
    namespace: "ext_s3"
    task: "tasks/s3/main.s3.yml"
    schema: "tasks/s3/schema.s3.yml"
    validator: "tasks/s3/validator.s3.yml"
    credentials:
      s3: "s3"
    params:
      list:
        - bucket: "{{ params.backup_bucket_name | default('') }}"
          permission: "private"
  s3_replica_buckets:
    base_dir: "ext-cloud"
    namespace: "ext_s3"
    task: "tasks/s3/main.s3.yml"
    schema: "tasks/s3/schema.s3.yml"
    validator: "tasks/s3/validator.s3.yml"
    credentials:
      s3: "s3"
    params:
      list:
        - bucket: "{{ params.backup_replica_bucket_name | default('') }}"
          permission: "private"
  node_dns_service:
    base_dir: "ext-cloud"
    namespace: "ext_dns"
    task: >-
      tasks/dns/{{
        params.dns_provider | default('')
      }}/{{
        params.dns_provider | default('')
      }}.main.dns.yml
    schema: >-
      tasks/dns/{{
        params.dns_provider | default('')
      }}/{{
        params.dns_provider | default('')
      }}.schema.dns.yml
    validator: >-
      tasks/dns/{{
        params.dns_provider | default('')
      }}/{{
        params.dns_provider | default('')
      }}.validator.dns.yml
    credentials:
      dns: "{{ params.dns_provider | default('') }}"
    params:
      zone: "{{ params.main_domain | default('') }}"
  digital_ocean_vpn:
    base_dir: "ext-cloud"
    namespace: "ext_vpn"
    task: "tasks/vpn/digital_ocean/digital_ocean.main.vpn.yml"
    schema: "tasks/vpn/digital_ocean/digital_ocean.schema.vpn.yml"
    validator: "tasks/vpn/digital_ocean/digital_ocean.validator.vpn.yml"
    credentials:
      vpn: "digital_ocean"
    params:
      tags:
        - "auto"
        - "prometheus"
        - "prometheus-web"
        - "prometheus-dmz"
      firewalls:
        - name: "private"
          tags: ["auto"]
          inbound_rules:
            - ports: "9080"
              sources:
                addresses: "{{ params.private_ips | default([]) }}"
            - ports: "9443"
              sources:
                addresses: "{{ params.private_ips | default([]) }}"
        - name: "auto"
          tags: ["auto"]
          inbound_rules:
            - ports: "22"
              sources:
                tags: ["main"]
                addresses: "{{ params.private_ips | default([]) }}"
          outbound_rules:
            - protocol: "tcp"
              ports: "1-65535"
              destinations:
                addresses: ["0.0.0.0/0", "::/0"]
            - protocol: "udp"
              ports: "1-65535"
              destinations:
                addresses: ["0.0.0.0/0", "::/0"]
            - protocol: "icmp"
              ports: "1-65535"
              destinations:
                addresses: ["0.0.0.0/0", "::/0"]
        - name: "prometheus"
          tags: ["prometheus"]
          inbound_rules:
            - ports: "9090"
              sources:
                tags: ["auto", "prometheus-web"]
        - name: "prometheus-web"
          tags: ["prometheus-web"]
          inbound_rules:
            - ports: "80"
              sources:
                tags: ["prometheus-dmz"]
            - ports: "443"
              sources:
                tags: ["prometheus-dmz"]
        - name: "prometheus-dmz"
          tags: ["prometheus-dmz"]
          inbound_rules:
            - ports: "80"
              sources:
                addresses: ["0.0.0.0/0", "::/0"]
            - ports: "443"
              sources:
                addresses: ["0.0.0.0/0", "::/0"]
  digital_ocean_node:
    base_dir: "ext-cloud"
    namespace: "ext_node"
    task: "tasks/node/digital_ocean/digital_ocean.main.node.yml"
    schema: "tasks/node/digital_ocean/digital_ocean.schema.node.yml"
    validator: "tasks/node/digital_ocean/digital_ocean.validator.node.yml"
    credentials:
      node: "digital_ocean"
    params:
      image_id: "ubuntu-18-04-x64"
      ipv6: true
      region_id: "ams3"
      size_id: "s-2vcpu-2gb"
    contents:
      user_data:
        type: "env"
        name: "user_data_ubuntu"
  linode:
    base_dir: "ext-cloud"
    namespace: "ext_node"
    task: "tasks/node/linode/linode.main.node.yml"
    schema: "tasks/node/linode/linode.schema.node.yml"
    validator: "tasks/node/linode/linode.validator.node.yml"
    credentials:
      node: "linode"
    params:
      image: "linode/ubuntu18.04"
      region: "us-east"
      type: "g6-standard-1"
    contents:
      user_data:
        type: "env"
        name: "user_data_ubuntu"
nodes:
  prometheus_local:
    credentials:
      host: "localhost"
    pods:
      - name: "prometheus"
        params:
          local: true
          named_volumes: "{{ params.named_volumes | default(false) }}"
          custom_ssl: "{{ params.local_custom_ssl | default({}) }}"
          enable_logs_setup: false
          enable_sync_setup: false
          main_domain: "{{ params.local_main_domain | default('localhost') }}"
          domains: "{{ params.local_domains | default({}) }}"
          ports:
            public_http_port: "8080"
            public_https_port: "8443"
            private_http_port: "9080"
            private_https_port: "9443"
        group_params:
          db_backup: "db_backup_no_sync"
  prometheus:
    service:
      name: "{{ params.node_service | default('skip') }}"
      params:
        tags:
          - "auto"
          - "prometheus-dmz"
    dns_service: "node_dns_service"
    base_dir: "/var/cloud"
    root: true
    credentials:
      host: "host"
    params:
      dns_service_params_list: "{{ params.dns_service_params_list | default([]) }}"
      host_users:
        - name: "host"
          setup_log_file: "/var/log/setup.log"
          setup_finished_log_regex: "^Setup Finished.*$"
          setup_success_log_last_line: "Setup Finished - Success"
          initial_connection_timeout: 90
          setup_finished_timeout: 300
    pods:
      - name: "prometheus"
        params:
          local: false
          domains: "{{ params.domains | default({}) }}"
          ports:
            public_http_port: "80"
            public_https_port: "443"
            private_http_port: "9080"
            private_https_port: "9443"
pods:
  prometheus:
    repo: "pod"
    root: "yes"
    ctx: "ext-pod/prometheus/prometheus.ctx.yml"
    schema: "ext-pod/prometheus/prometheus.schema.yml"
    validator: "ext-pod/prometheus/prometheus.validator.yml"
    fast_prepare: "true"
    ext_repos:
      - repo: "ext_pod"
        dir: "ext-pod"
    credentials:
      grafana: "grafana"
      minio_gateway: "{{ params.use_s3 | default(false) | bool | ternary('minio_gateway', '') }}"
      backup_bucket: "{{ params.use_s3 | default(false) | bool | ternary('s3', '') }}"
      backup_replica_bucket: "{{ params.use_s3 | default(false) | bool | ternary('s3_replica', '') }}"
    params:
      type: "app"
      orchestration: "docker_compose"
      custom_dir: "ext-pod"
      custom_dir_sync: "{{ params.pod_custom_dir_sync | default(false) }}"
      meta: "{{ params.pod_meta | default({}) }}"
      main_domain: "{{ params.main_domain | default('') }}"
      use_ssl: "{{ params.use_ssl | default(false) }}"
      use_pod_prefix: "{{ params.use_pod_prefix | default(false) }}"
      use_pod_full_prefix: "{{ params.use_pod_full_prefix | default(false) }}"
      use_node_exporter: "{{ params.use_node_exporter | default(false) }}"
      use_cadvisor: "{{ params.use_cadvisor | default(false) }}"
      use_nginx: "{{ params.use_nginx | default(true) }}"
      use_theia: "{{ params.use_theia | default(false) }}"
      use_minio_gateway: "{{ params.use_minio_gateway | default(false) }}"
      use_filestash: "{{ params.use_filestash | default(false) }}"
      use_s3: "{{ params.use_s3 | default(false) }}"
      use_fluentd: "{{ params.use_fluentd | default(false) }}"
      use_certbot: "{{ params.use_certbot | default(false) }}"
      use_private_path: "{{ params.use_private_path | default(false) }}"
      auth_file: "{{ params.auth_file | default('') }}"
      s3_cli: "{{ params.s3_cli | default('') }}"
      define_s3_backup_lifecycle: "{{ params.define_s3_backup_lifecycle | default(false) }}"
      s3_backup_lifecycle_file: "s3-backup-lifecycle.json"
      define_cron: "{{ params.define_cron | default(false) }}"
      include_cron_watch: "{{ params.include_cron_watch | default(false) }}"
      cron_src: "env/cron/cron-file"
      cron_dest: "/var/spool/cron/crontabs/root"
      backup_bucket_name: "{{ params.backup_bucket_name | default('') }}"
      backup_bucket_path: "{{ params.backup_bucket_path | default('') }}"
      backup_replica_bucket_name: "{{ params.backup_replica_bucket_name | default('') }}"
      backup_replica_bucket_path: "{{ params.backup_replica_bucket_path | default('') }}"
      restore_db: "{{ params.restore_db | default(false) }}"
      enable_db_backup: "{{ params.enable_db_backup | default(false) }}"
      enable_db_setup: "{{ params.enable_db_setup | default(false) }}"
      enable_logs_backup: "{{ params.enable_logs_backup | default(false) }}"
      enable_logs_setup: "{{ params.enable_logs_setup | default(false) }}"
      enable_sync_backup: "{{ params.enable_sync_backup | default(false) }}"
      enable_sync_setup: "{{ params.enable_sync_setup | default(false) }}"
      enable_backup_replica: "{{ params.enable_backup_replica | default(false) }}"
      certbot:
        email: "{{ params.certbot_email | default('') }}"
        staging: "{{ params.certbot_staging | default(false) }}"
        force: "{{ params.certbot_force | default(false) }}"
      services:
        fluentd:
          port: "24224"
        prometheus:
          port: "9090"
        grafana:
          port: "3000"
      images:
        nginx_image: "nginx"
        nginx_version: "1.14.2-alpine"
        prometheus_image: "prom/prometheus"
        prometheus_version: "v2.20.1"
        grafana_image: "grafana/grafana"
        grafana_version: "7.1.5"
        node_exporter_image: "prom/node-exporter"
        node_exporter_version: "v1.0.1"
        cadvisor_image: "google/cadvisor"
        cadvisor_version: "v0.33.0"
        theia_image: "theiaide/theia"
        theia_version: "1.3.0"
        minio_gateway_image: "minio/minio"
        minio_gateway_version: "RELEASE.2020-07-02T00-15-09Z"
        filestash_image: "machines/filestash"
        filestash_version: "4cbeb2c"
        toolbox_image: "lucasbasquerotto/image"
        toolbox_version: "toolbox-20200715-02"
        certbot_image: "certbot/certbot"
        certbot_version: "v1.2.0"
        awscli_image: "lucasbasquerotto/aws-cli"
        awscli_version: "1.0.0"
        mc_image: "minio/mc"
        mc_version: "RELEASE.2021-03-12T03-36-59Z"
        rclone_image: "rclone/rclone"
        rclone_version: "1.54.0"
        logrotator_image: "python"
        logrotator_version: "3.8.4-buster"
        fluentd_image: "lucasbasquerotto/image"
        fluentd_version: "fluentd-20200617"
    group_params:
      memory: "memory_app"
      db_setup: >-
        {{
        params.non_s3_setup | default(false) | bool |
        ternary('db_setup_restore_file', 'db_setup_restore_s3')
        }}
      db_backup: "db_backup_sync"
    transfer:
      - dest: "env/cron/cron-file"
        when: "{{ params.define_cron | default(false) }}"
        src:
          type: "template"
          origin: "cloud"
          file: "ext-cloud/files/cron/pod.tpl.sh"
          schema: "ext-cloud/files/cron/pod.schema.yml"
          params:
            tasks:
              - name: "watch"
                when: "{{ params.include_cron_watch | default(false) | bool }}"
                task: "shared:watch"
                cron: "*/1 * * * *"
              - name: "exec_general_actions"
                task: "action:exec:general_actions"
                cron: >-
                  {{
                    (params.include_cron_watch | default(false) | bool)
                    | ternary('0 */1 * * *', '*/5 * * * *')
                  }}
              - name: "exec_backup_actions"
                task: "action:exec:backup_actions"
                cron: >-
                  {{
                    (params.include_cron_watch | default(false) | bool)
                    | ternary('0 */1 * * *', '*/5 * * * *')
                  }}
              - name: "create_actions_main"
                task: "shared:create_actions:main"
                cron: "*/5 * * * *"
              - name: "create_actions_log"
                task: "shared:create_actions:log"
                cron: "*/5 * * * *"
              - name: "create_actions_frequent"
                task: "shared:create_actions block_ips"
                cron: "*/15 * * * *"
              - name: "create_actions_full_log"
                task: "shared:create_actions logrotate log_summary"
                cron: "* */1 * * *"
              - name: "create_actions_backup"
                task: "shared:create_actions backup"
                cron: "0 */6 * * *"
              - name: "create_actions_replicate_s3"
                task: "shared:create_actions replicate_s3"
                cron: "3 */1 * * *"
      - dest: "env/{{ params.s3_cli | default('') }}/etc/s3-backup-lifecycle.json"
        when: "{{ params.define_s3_backup_lifecycle | default(false) | bool }}"
        src:
          type: "template"
          origin: "cloud"
          file: "ext-cloud/files/s3/s3_lifecycle.json.j2"
          schema: "ext-cloud/files/s3/s3_lifecycle.schema.yml"
          params:
            rules:
              - name: "logs-expiration"
                filter_prefix: "logs/"
                expiration_days: 30
                older_versions_expiration_days: 180
pod_group_params:
  memory_app:
    nginx: 512mb
    grafana: 512mb
    prometheus: 1gb
    node_exporter: 512mb
    cadvisor: 512mb
    theia: 512mb
    minio_gateway: 512mb
    filestash: 512mb
    toolbox: 512mb
    certbot: 256mb
    s3_cli: 512mb
    fluentd: 256mb
  memory_db:
    prometheus: 1gb
    node_exporter: 512mb
    cadvisor: 512mb
    toolbox: 512mb
    s3_cli: 512mb
    fluentd: 256mb
  memory_web:
    nginx: 512mb
    grafana: 512mb
    node_exporter: 512mb
    cadvisor: 512mb
    theia: 512mb
    minio_gateway: 512mb
    filestash: 512mb
    toolbox: 512mb
    certbot: 256mb
    s3_cli: 512mb
    fluentd: 256mb
  db_backup_sync:
    backup_bucket_sync_dir: "db"
  db_backup_no_sync:
    is_compressed_file: true
  db_setup_restore_file:
    restore_use_s3: false
    restore_remote_file: "https://github.com/lucasbasquerotto/backups/blob/master/prometheus/db/20200624_214700.zip?raw=true"
    is_compressed_file: true
  db_setup_restore_s3:
    restore_use_s3: true
    restore_s3_sync: true
    restore_remote_bucket_path_dir: "db"
tasks:
  docker_compose_install:
    type: "task"
    root: true
    file: "ext-cloud/run-tasks/docker.yml"
    schema: "ext-cloud/run-tasks/docker.schema.yml"
    params:
      compose:
        version: "1.27.2"
  main_build:
    type: "shell"
    root: true
    cmd: "./run build"
  main_upgrade:
    type: "shell"
    root: true
    cmd: "./run upgrade"
contents:
  user_data_ubuntu:
    type: "template"
    origin: "cloud"
    file: "ext-cloud/files/user-data/ubuntu-18.04.tpl.sh"
    schema: "ext-cloud/files/user-data/ubuntu-18.04.schema.yml"
    params:
      user_directories: ["/var/cloud"]
      install_docker: true
      install_podman: false
      install_packages: true
    credentials:
      node: "host"
    contents:
      host_ssh_public_keys: "{{ params.host_ssh_public_keys_content | default('') }}"
repos:
  cloud:
    src: "https://github.com/lucasbasquerotto/cloud.git"
    version: "master"
  ext_cloud:
    src: "https://github.com/lucasbasquerotto/ext-cloud.git"
    version: "master"
  pod:
    src: "https://github.com/lucasbasquerotto/pod.git"
    version: "master"
  ext_pod:
    src: "https://github.com/lucasbasquerotto/ext-pod.git"
    version: "master"
credentials: "{{ credentials }}"
