#!/bin/bash
set -eou pipefail

mkdir -p /main/files/ctl/
mkdir -p /main/secrets/ctl/

envsubst < /tmp/main/vars.tpl.yml > /main/files/ctl/vars.yml
mv /tmp/main/vars.sh /main/files/ctl/vars.sh
mv /tmp/main/run /main/files/ctl/run
echo "123456" > /main/secrets/ctl/vault

if [ ! -d /env ]; then
	echo "[error] directory /env doesn't exist"
fi

env_dir="/main/dev/repos/env"
mkdir -p "$env_dir"
chmod 777 "$env_dir"
rm -rf "$env_dir/.git"
mv "/tmp/env/.git" "$env_dir/.git"
rm -rf "$env_dir/common"
ln -rsfT "/env" "$env_dir/common"

exec /main/files/ctl/run --inside "$@"