#!/bin/bash
set -eou pipefail

mkdir -p /main/files/ctl/
mkdir -p /main/secrets/ctl/

envsubst < /tmp/main/vars.tpl.yml > /main/files/ctl/vars.yml
mv /tmp/main/vars.sh /main/files/ctl/vars.sh
mv /tmp/main/run /main/files/ctl/run
echo "123456" > /main/secrets/ctl/vault
